main:
  - name: "Home"
    url: "/"
    weight: 1

  - name: "Projects"
    url: "/projects/"
    weight: 2

  - name: "Publications"
    url: "/publications/"
    weight: 3

  - name: "News"
    url: "/news/"
    weight: 4

  - name: "Blog"
    url: "/blog/"
    weight: 5

  - name: "Awards"
    url: "/awards/"
    weight: 6

  - name: "Resume"
    url: "/uploads/resume.pdf"
    weight: 7
